/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador_FRM_MenuPrincipal;

/**
 *
 * @author Yenssy
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    
    public FRM_MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        controlador_FRM_MenuPrincipal =  new Controlador_FRM_MenuPrincipal(this);
        
        jbtn_Jugar.addActionListener(controlador_FRM_MenuPrincipal);
        jbtn_Puntuacion.addActionListener(controlador_FRM_MenuPrincipal);
        jbtn_Instrucciones.addActionListener(controlador_FRM_MenuPrincipal);
    }//fin constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_Jugar = new javax.swing.JButton();
        jbtn_Puntuacion = new javax.swing.JButton();
        jbtn_Instrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_juego/boton-de-play.png"))); // NOI18N
        jbtn_Jugar.setActionCommand("Jugar");
        jbtn_Jugar.setBorderPainted(false);
        jbtn_Jugar.setContentAreaFilled(false);
        getContentPane().add(jbtn_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jbtn_Puntuacion.setText("Puntuacion");
        getContentPane().add(jbtn_Puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 105, -1));

        jbtn_Instrucciones.setText("Instrucciones");
        getContentPane().add(jbtn_Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 105, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_juego/tortuga(1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_juego/liebre.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_juego/fondo - copia1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtn_Instrucciones;
    private javax.swing.JButton jbtn_Jugar;
    private javax.swing.JButton jbtn_Puntuacion;
    // End of variables declaration//GEN-END:variables
}
